### ISSUE TITLE
Player health

### ISSUE THREAD

**Issue by rafaelgonzalez** [shapeshiftingrabbits/Shooter-MVP#9]
- Player starts with a certain amount of health, dies when health reaches 0.
- Enemies touching the player deplete its health instead of instantly killing.
- Enemies touching the player slow the character down. #10 
- Health bar is on the top right corner.
- Color red on grey

**Comment by LaurieTrichet** [comment]
updated description

**Comment by rafaelgonzalez** [comment]
Closed in #40
